image: jonaskello/docker-and-compose:latest
services:
- docker:dind

build:
  stage: build
  script:
    - echo $TOKEN      
    - docker login -u ahushh -p $TOKEN registry.gitlab.com
    - sh ./build.sh
    - docker-compose build
    - docker-compose push
