image: jonaskello/docker-and-compose:latest
services:
  - docker:dind

stages:
  - build
  - deploy

build-monaba:
  stage: build
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD registry.gitlab.com
    - sh ./build.sh
    - docker-compose pull
    - docker-compose build
    - docker-compose push

deploy-to-server:
  stage: deploy
  when: manual
  before_script:
    - apk update && apk add 
    - 'which ssh-agent || ( apk update -y && apk add openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
  script:
    - ssh -t "$SSH_USER"@"$SSH_HOST" "cd $REPO_PATH && docker-compose pull && docker-compose down && docker-compose up -d"

