# remove .dockerignore
version: "3.7"
services:
  db:
    image: postgres:10
    hostname: db
    env_file: env_prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main
  webserver:
    build: ./webserver
    hostname: monaba.in
    image: monaba/webserver
    ports:
      - "80:80"
    volumes:
      - ./monaba/upload:/opt/monaba/upload
    extra_hosts:
      app: 127.0.0.1
    network_mode: host  

  search:
    build: ./search
    hostname: search.in
    image: monaba/search
    ports:
      - "9312:9312"
    volumes:
      - searchdata:/var/lib/sphinxsearch/data
    networks:
      - main
volumes:
  pgdata:
  searchdata:
networks:
  main:
    driver: bridge
