version: "3.3"
services:
  db:
    image: postgres:10
    env_file: env_prod
    volumes:
      - ./storage/pgdata:/var/lib/postgresql/data
    networks:
      main:
        ipv4_address: 172.19.0.6
    deploy:
      placement:
        constraints: [node.role == manager]
  app:
    build: ./monaba
    hostname: monaba.in
    image: docker.pkg.github.com/ahushh/monaba/app:latest
    command: /opt/monaba/Monaba /var/settings.yml
    env_file: env_prod  
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./storage/upload:/opt/monaba/upload
      - ./storage/banners:/opt/monaba/static/banners
      - ./settings.yml:/var/settings.yml
    tmpfs:
      - /opt/monaba/static/tmp:size=1G
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 2s
    networks:
      main:
        ipv4_address: 172.19.0.5
  webserver:
    build: ./webserver
    image: docker.pkg.github.com/ahushh/monaba/webserver:latest
    ports:
      - "80:80"
    links:
      - app  
    volumes:
      - ./storage/upload:/opt/monaba/upload
    networks:
      main:
        ipv4_address: 172.19.0.4
    deploy:
      placement:
        constraints: [node.role == manager]
  search:
    build: ./search
    hostname: search.in
    image: docker.pkg.github.com/ahushh/monaba/search:latest
    links:
      - app
    depends_on:
      - app
    volumes:
      - ./storage/searchdata:/var/lib/sphinxsearch/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      main:
        ipv4_address: 172.19.0.3
        aliases:
          - search.in
  torgate:
    build: ./torgate
    image: docker.pkg.github.com/ahushh/monaba/torgate:latest
    env_file: env_prod
    links:
      - webserver
    networks:
      main:
        ipv4_address: 172.19.0.2
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 2s
        monitor: 2s
networks:
  main:    
    ipam:
      config:
        - subnet: 172.19.0.0/16

