version: "3.3"
services:
  database:
    image: postgres
    env_file:
      - database/dev_env
    ports:
      - "5432:5432"
  monaba:
    build: ./monaba
    image: monaba
    command: /opt/monaba/Monaba
    #command: yesod devel
    environment:
      - PGHOST=database
    depends_on:
      - database
    tty:
      false
    ports:
      - "3000:3000"
    volumes:
      - upload:/opt/server/upload

volumes:
  upload: