name:                MonabaCaptcha
version:             2.5.0.0

executables:
  PlainCaptcha:
    main:                Main.hs
    source-dirs:         Plain
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 4.9
    - imagemagick
    - text
    - transformers
    - random
  YobaCaptcha:
    main:                Main.hs
    source-dirs:         Yoba
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 4.9
    - imagemagick
    - text
    - transformers
    - random
