# NOTE: These settings can be overridden by environment variables as well, in
# particular:
#
#    PGHOST
#    PGPORT
#    PGUSER
#    PGPASS
#    PGDATABASE

Default: &defaults
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  database: monabas
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: monabas_test
  <<: *defaults

Staging:
  database: monabas_staging
  poolsize: 100
  <<: *defaults

Production:
  database: monabas_production
  poolsize: 100
  <<: *defaults
