Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: " "
  #analytics: UA-YOURCODE
  sitename: "Monaba"
  geoipcitypath: "/usr/share/GeoIP/GeoIPCity.dat"
  timezone: 14400 # default time offset in seconds
  stylesheet: Chaos # default stylesheet
  maxLenOfPostTitle: 60
  maxLenOfPostName: 20
  captcha: "./Captcha"
  maxLenOfFileName: 20

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://haibane.ru"
  sitename: "Хайбане.ru"
  <<: *defaults
