# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

upload-dir:     "upload"
static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:httзнp://localhost" # change to your domain
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
  user:     "_env:PGUSER:postgres"
  password: "_env:PGPASS:postgres"
  host:     "_env:PGHOST:localhost"
  port:     "_env:PGPORT:5432"
  database: "_env:PGDATABASE:monabas"
  poolsize: "_env:PGPOOLSIZE:100"

footer: Insert copyright statement here
#analytics: UA-YOURCODE

sitename:          "Monaba"
geoipcitypath:     "/usr/share/GeoIP/GeoIPCity.dat"
timezone:          14400 # default time offset in seconds, see Handler/Settings.hs for list of timezones and offsets
stylesheet:        Chaos # default stylesheet (Ash, Futaba, Chaos, Chaosfm, Mayuri, Nox or whatever you put into static/stylesheets directory)
maxLenOfPostTitle: 60
maxLenOfPostName:  20
maxLenOfFileName:  40
captcha:           "dist/build/Captcha/Captcha" # takes a path to captcha image (must generate a png file) as the first argument and prints captcha text to STDIN
metaKeywords:      "haskell,yesod"
metaDescription:   "haskell imageboard"
titleDelimiter:    " / "
ffmpeg:            "/usr/bin/ffmpeg"
exiftool:          "/usr/bin/exiftool"
animatedThumbs:    false