flags: {}
extra-package-dbs: []
packages:
- '.'
- nano-md5-0.1.2/
extra-deps:
- imagemagick-0.0.4.2
- path-pieces-0.1.5
- text-1.2.2.1
- vector-0.10.12.3
- yaml-0.8.18
system-ghc: true
resolver: lts-6.7
