flags: {}
extra-package-dbs: []
packages:
- '.'
- nano-md5-0.1.2/
extra-deps:
#- path-pieces-0.1.5
#- text-1.2.2.1
#- vector-0.10.12.3
# - yaml-0.8.18
# system-ghc: true
resolver: lts-13.12
extra-include-dirs:
- /usr/local/opt/openssl@1.1/include
- /usr/local/opt/icu4c/include
extra-lib-dirs:
- /usr/local/opt/openssl@1.1/lib
- /usr/local/opt/icu4c/lib
